-include xdebug.dep
xdebug.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/xdebug.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/xdebug.c -o xdebug.lo  -MMD -MF xdebug.dep -MT xdebug.lo
-include src/base/base.dep
src/base/base.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/base/base.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/base/base.c -o src/base/base.lo  -MMD -MF src/base/base.dep -MT src/base/base.lo
-include src/base/ctrl_socket.dep
src/base/ctrl_socket.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/base/ctrl_socket.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/base/ctrl_socket.c -o src/base/ctrl_socket.lo  -MMD -MF src/base/ctrl_socket.dep -MT src/base/ctrl_socket.lo
-include src/base/filter.dep
src/base/filter.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/base/filter.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/base/filter.c -o src/base/filter.lo  -MMD -MF src/base/filter.dep -MT src/base/filter.lo
-include src/lib/usefulstuff.dep
src/lib/usefulstuff.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/usefulstuff.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/usefulstuff.c -o src/lib/usefulstuff.lo  -MMD -MF src/lib/usefulstuff.dep -MT src/lib/usefulstuff.lo
-include src/lib/cmd_parser.dep
src/lib/cmd_parser.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/cmd_parser.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/cmd_parser.c -o src/lib/cmd_parser.lo  -MMD -MF src/lib/cmd_parser.dep -MT src/lib/cmd_parser.lo
-include src/lib/compat.dep
src/lib/compat.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/compat.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/compat.c -o src/lib/compat.lo  -MMD -MF src/lib/compat.dep -MT src/lib/compat.lo
-include src/lib/crc32.dep
src/lib/crc32.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/crc32.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/crc32.c -o src/lib/crc32.lo  -MMD -MF src/lib/crc32.dep -MT src/lib/crc32.lo
-include src/lib/file.dep
src/lib/file.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/file.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/file.c -o src/lib/file.lo  -MMD -MF src/lib/file.dep -MT src/lib/file.lo
-include src/lib/hash.dep
src/lib/hash.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/hash.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/hash.c -o src/lib/hash.lo  -MMD -MF src/lib/hash.dep -MT src/lib/hash.lo
-include src/lib/headers.dep
src/lib/headers.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/headers.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/headers.c -o src/lib/headers.lo  -MMD -MF src/lib/headers.dep -MT src/lib/headers.lo
-include src/lib/lib.dep
src/lib/lib.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/lib.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/lib.c -o src/lib/lib.lo  -MMD -MF src/lib/lib.dep -MT src/lib/lib.lo
-include src/lib/llist.dep
src/lib/llist.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/llist.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/llist.c -o src/lib/llist.lo  -MMD -MF src/lib/llist.dep -MT src/lib/llist.lo
-include src/lib/log.dep
src/lib/log.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/log.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/log.c -o src/lib/log.lo  -MMD -MF src/lib/log.dep -MT src/lib/log.lo
-include src/lib/set.dep
src/lib/set.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/set.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/set.c -o src/lib/set.lo  -MMD -MF src/lib/set.dep -MT src/lib/set.lo
-include src/lib/str.dep
src/lib/str.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/str.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/str.c -o src/lib/str.lo  -MMD -MF src/lib/str.dep -MT src/lib/str.lo
-include src/lib/timing.dep
src/lib/timing.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/timing.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/timing.c -o src/lib/timing.lo  -MMD -MF src/lib/timing.dep -MT src/lib/timing.lo
-include src/lib/var.dep
src/lib/var.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var.c -o src/lib/var.lo  -MMD -MF src/lib/var.dep -MT src/lib/var.lo
-include src/lib/var_export_html.dep
src/lib/var_export_html.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_html.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_html.c -o src/lib/var_export_html.lo  -MMD -MF src/lib/var_export_html.dep -MT src/lib/var_export_html.lo
-include src/lib/var_export_line.dep
src/lib/var_export_line.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_line.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_line.c -o src/lib/var_export_line.lo  -MMD -MF src/lib/var_export_line.dep -MT src/lib/var_export_line.lo
-include src/lib/var_export_text.dep
src/lib/var_export_text.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_text.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_text.c -o src/lib/var_export_text.lo  -MMD -MF src/lib/var_export_text.dep -MT src/lib/var_export_text.lo
-include src/lib/var_export_xml.dep
src/lib/var_export_xml.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_xml.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/var_export_xml.c -o src/lib/var_export_xml.lo  -MMD -MF src/lib/var_export_xml.dep -MT src/lib/var_export_xml.lo
-include src/lib/xml.dep
src/lib/xml.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/xml.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/lib/xml.c -o src/lib/xml.lo  -MMD -MF src/lib/xml.dep -MT src/lib/xml.lo
-include src/coverage/branch_info.dep
src/coverage/branch_info.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/coverage/branch_info.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/coverage/branch_info.c -o src/coverage/branch_info.lo  -MMD -MF src/coverage/branch_info.dep -MT src/coverage/branch_info.lo
-include src/coverage/code_coverage.dep
src/coverage/code_coverage.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/coverage/code_coverage.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/coverage/code_coverage.c -o src/coverage/code_coverage.lo  -MMD -MF src/coverage/code_coverage.dep -MT src/coverage/code_coverage.lo
-include src/debugger/com.dep
src/debugger/com.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/com.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/com.c -o src/debugger/com.lo  -MMD -MF src/debugger/com.dep -MT src/debugger/com.lo
-include src/debugger/debugger.dep
src/debugger/debugger.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/debugger.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/debugger.c -o src/debugger/debugger.lo  -MMD -MF src/debugger/debugger.dep -MT src/debugger/debugger.lo
-include src/debugger/handler_dbgp.dep
src/debugger/handler_dbgp.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/handler_dbgp.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/handler_dbgp.c -o src/debugger/handler_dbgp.lo  -MMD -MF src/debugger/handler_dbgp.dep -MT src/debugger/handler_dbgp.lo
-include src/debugger/handlers.dep
src/debugger/handlers.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/handlers.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/handlers.c -o src/debugger/handlers.lo  -MMD -MF src/debugger/handlers.dep -MT src/debugger/handlers.lo
-include src/debugger/ip_info.dep
src/debugger/ip_info.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/ip_info.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/debugger/ip_info.c -o src/debugger/ip_info.lo  -MMD -MF src/debugger/ip_info.dep -MT src/debugger/ip_info.lo
-include src/develop/develop.dep
src/develop/develop.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/develop.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/develop.c -o src/develop/develop.lo  -MMD -MF src/develop/develop.dep -MT src/develop/develop.lo
-include src/develop/monitor.dep
src/develop/monitor.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/monitor.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/monitor.c -o src/develop/monitor.lo  -MMD -MF src/develop/monitor.dep -MT src/develop/monitor.lo
-include src/develop/php_functions.dep
src/develop/php_functions.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/php_functions.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/php_functions.c -o src/develop/php_functions.lo  -MMD -MF src/develop/php_functions.dep -MT src/develop/php_functions.lo
-include src/develop/stack.dep
src/develop/stack.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/stack.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/stack.c -o src/develop/stack.lo  -MMD -MF src/develop/stack.dep -MT src/develop/stack.lo
-include src/develop/superglobals.dep
src/develop/superglobals.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/superglobals.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/develop/superglobals.c -o src/develop/superglobals.lo  -MMD -MF src/develop/superglobals.dep -MT src/develop/superglobals.lo
-include src/gcstats/gc_stats.dep
src/gcstats/gc_stats.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/gcstats/gc_stats.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/gcstats/gc_stats.c -o src/gcstats/gc_stats.lo  -MMD -MF src/gcstats/gc_stats.dep -MT src/gcstats/gc_stats.lo
-include src/profiler/profiler.dep
src/profiler/profiler.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/profiler/profiler.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/profiler/profiler.c -o src/profiler/profiler.lo  -MMD -MF src/profiler/profiler.dep -MT src/profiler/profiler.lo
-include src/tracing/trace_computerized.dep
src/tracing/trace_computerized.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_computerized.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_computerized.c -o src/tracing/trace_computerized.lo  -MMD -MF src/tracing/trace_computerized.dep -MT src/tracing/trace_computerized.lo
-include src/tracing/trace_flamegraph.dep
src/tracing/trace_flamegraph.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_flamegraph.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_flamegraph.c -o src/tracing/trace_flamegraph.lo  -MMD -MF src/tracing/trace_flamegraph.dep -MT src/tracing/trace_flamegraph.lo
-include src/tracing/trace_html.dep
src/tracing/trace_html.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_html.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_html.c -o src/tracing/trace_html.lo  -MMD -MF src/tracing/trace_html.dep -MT src/tracing/trace_html.lo
-include src/tracing/trace_textual.dep
src/tracing/trace_textual.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_textual.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/trace_textual.c -o src/tracing/trace_textual.lo  -MMD -MF src/tracing/trace_textual.dep -MT src/tracing/trace_textual.lo
-include src/tracing/tracing.dep
src/tracing/tracing.lo: /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/tracing.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -DZEND_COMPILE_DL_EXT=1 -c /home/vandunxg/CODE/hotel/hostay/xdebug-3.3.2/src/tracing/tracing.c -o src/tracing/tracing.lo  -MMD -MF src/tracing/tracing.dep -MT src/tracing/tracing.lo
$(phplibdir)/xdebug.la: ./xdebug.la
	$(LIBTOOL) --tag=CC --mode=install cp ./xdebug.la $(phplibdir)

./xdebug.la: $(shared_objects_xdebug) $(XDEBUG_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_xdebug) $(XDEBUG_SHARED_LIBADD)

